In [25]:
import pandas as pd

In [44]:
Customers = pd.read_csv('CCCustomers.csv')
Customers = Customers.sort_values('Customer_Since')

      Unnamed: 0  Customer_ID  Gender First name   Last name Date_of_birth  \
2740        2740         2158  Female      Rimas       Ammar    1997-01-12
4229        4229         4722  Female      Ireen     Maalouf    1981-05-26
19            19         1567    Male     Sajjad    AlHamdan    1966-01-05
9794        9794         6178  Female    Mahmuna   Benaldjia    1989-12-08
6502        6502         5192  Female  Boutheina  Al-Zahrani    1996-07-09
...          ...          ...     ...        ...         ...           ...
1091        1091          792    Male   Ziauddin  As-Suwaidi    1959-11-08
63            63         4057  Female     Sandra       Jaber    1994-06-05
7785        7785         4468  Female    Mahmuna     Gaddafi    1997-03-18
3309        3309         5948    Male     Sajjad     Qureshi    1990-06-25
4543        4543         9099  Female       Afaf      Shihuh    1998-01-25

     Agree_for_promo autoplay_card                        Customer_Email  \
2740             Yes           Yes             RimasAmmar48@zajil.net.sa
4229              No            No             IreenMaalouf51@sol.net.sa
19                No            No    SajjadAlHamdan26@saudia-omline.com
9794             Yes            No      MahmunaBenaldjia80@naseej.com.sa
6502             Yes            No  BoutheinaAl-Zahrani26@compuserve.com
...              ...           ...                                   ...
1091             Yes           Yes     ZiauddinAs-Suwaidi5@aramco.com.sa
63               Yes            No           SandraJaber10@naseej.com.sa
7785             Yes           Yes        MahmunaGaddafi68@aramco.com.sa
3309              No            No           SajjadQureshi11@123arab.com
4543             Yes            No            AfafShihuh26@naseej.com.sa

               MSISDN    Status  Category Customer_Since     Region Language  \
2740  +996-59-4904568    Active  Physical     2020-01-01     Riyadh   Arabic
4229  +996-55-5916350    Active  Physical     2020-01-01      Mecca   Arabic
19    +996-58-3145082  Inactive  Physical     2020-01-01    Al-Jawf   Arabic
9794  +996-55-7400233  Inactive  Physical     2020-01-01  Al-Qassim   Arabic
6502  +996-59-6857082    Active  Physical     2020-01-01     Riyadh   Arabic
...               ...       ...       ...            ...        ...      ...
1091  +996-58-7997752  Inactive  Physical     2022-04-19      Mecca   Arabic
63    +996-58-7306807  Inactive  Physical     2022-04-19     Riyadh   Arabic
7785  +996-50-7422199  Inactive  Physical     2022-04-19      Mecca   Arabic
3309  +996-56-0103981  Inactive  Physical     2022-04-19      Mecca   Arabic
4543  +996-54-6691895  Inactive  Business     2022-04-20     Riyadh   Arabic

     termination_date  Customer_City Customer_City_Type
2740       2022-11-27      Al-'Aflāj               city
4229       2022-03-11  Sarāt 'Abīdah               city
19         2022-03-20        Ar-Rass               city
9794       2022-11-27      Al-'Arḍah               city
6502       2022-10-05        Khaybar               city
...               ...            ...                ...
1091       2022-06-29       Ar-Riyāḍ               city
63         2022-11-24          Ḍamad               city
7785       2022-07-22         Rābigh               city
3309       2022-09-28         Rābigh               city
4543       2022-11-13      Al-'Arḍah               town

[9656 rows x 18 columns]

In [46]:
Customers_main = Customers[:9655]
Customers_main.to_csv('Customers.csv', index=False)
Customers_main.tail()

,Unnamed: 0,Customer_ID,Gender,First name,Last name,Date_of_birth,Agree_for_promo,autoplay_card,Customer_Email,MSISDN,Status,Category,Customer_Since,Region,Language,termination_date,Customer_City,Customer_City_Type
8693,8693,4646,Female,Rania,Khayat,1983-06-11,No,No,RaniaKhayat67@123arab.com,+996-55-4761420,Inactive,Physical,2022-04-19,Riyadh,Arabic,2022-07-19,Rābigh,city
1091,1091,792,Male,Ziauddin,As-Suwaidi,1959-11-08,Yes,Yes,ZiauddinAs-Suwaidi5@aramco.com.sa,+996-58-7997752,Inactive,Physical,2022-04-19,Mecca,Arabic,2022-06-29,Ar-Riyāḍ,city
63,63,4057,Female,Sandra,Jaber,1994-06-05,Yes,No,SandraJaber10@naseej.com.sa,+996-58-7306807,Inactive,Physical,2022-04-19,Riyadh,Arabic,2022-11-24,Ḍamad,city
7785,7785,4468,Female,Mahmuna,Gaddafi,1997-03-18,Yes,Yes,MahmunaGaddafi68@aramco.com.sa,+996-50-7422199,Inactive,Physical,2022-04-19,Mecca,Arabic,2022-07-22,Rābigh,city
3309,3309,5948,Male,Sajjad,Qureshi,1990-06-25,No,No,SajjadQureshi11@123arab.com,+996-56-0103981,Inactive,Physical,2022-04-19,Mecca,Arabic,2022-09-28,Rābigh,city

In [47]:
Customers_last = Customers[9655:]
Customers_last.to_csv('Customers_last.csv', index=False)
Customers_last

,Unnamed: 0,Customer_ID,Gender,First name,Last name,Date_of_birth,Agree_for_promo,autoplay_card,Customer_Email,MSISDN,Status,Category,Customer_Since,Region,Language,termination_date,Customer_City,Customer_City_Type
4543,4543,9099,Female,Afaf,Shihuh,1998-01-25,Yes,No,AfafShihuh26@naseej.com.sa,+996-54-6691895,Inactive,Business,2022-04-20,Riyadh,Arabic,2022-11-13,Al-'Arḍah,town
6619,6619,3924,Male,AbdulHaq,Reza,1996-07-14,Yes,No,AbdulHaqReza59@aramco.com.sa,+996-55-1530784,Active,Physical,2022-04-20,Riyadh,Arabic,2022-03-16,Al-Jubaīl,city
2839,2839,39,Male,Anjem,Taieb,1981-07-13,Yes,No,AnjemTaieb26@saudia-omline.com,+996-54-7897303,Inactive,Physical,2022-04-20,Riyadh,Arabic,2022-08-11,Ṣabyā,city
6579,6579,7781,Female,Katya,Latif,1965-09-27,No,No,KatyaLatif40@compuserve.com,+996-54-9504871,Active,Physical,2022-04-20,Riyadh,Arabic,2022-07-08,Khaybar,city
7524,7524,2688,Male,Anwar,Maatouk,1974-01-17,No,No,AnwarMaatouk27@arasco.net.sa,+996-53-8381231,Active,Physical,2022-04-20,Riyadh,Arabic,NaN,Al-Jumūm,city
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6526,6526,5062,Female,Julia,Trabelsi,1983-01-04,No,Yes,JuliaTrabelsi29@sps.net.sa,+996-56-3619496,Active,Physical,2022-05-19,Mecca,Arabic,2022-03-05,Afïf,city
3951,3951,4442,Male,Haydar,Abiha,1972-02-16,No,No,HaydarAbiha61@saudia-omline.com,+996-58-6123545,Active,Business,2022-05-19,Asir,Arabic,2022-03-05,Al-'Arḍah,city
2836,2836,6609,Female,Atikah,Batma,1973-02-13,No,No,AtikahBatma72@zajil.net.sa,+996-59-6879443,Active,Physical,2022-05-19,Mecca,Arabic,2022-08-13,Turubah,city
2568,2568,4258,Female,Mona,Nabhani,1993-08-05,Yes,No,MonaNabhani24@gmail.com,+996-55-5560331,Inactive,Physical,2022-05-19,Tabuk,Arabic,NaN,Rābigh,city
7875,7875,2445,Male,Saifullah,Nazif,2004-01-08,No,No,SaifullahNazif18@aramco.com.sa,+996-54-0885928,Inactive,Physical,2022-05-19,Mecca,Arabic,2022-03-25,Rābigh,town

In [29]:
All_information = pd.read_csv('AAAll_information.csv')#.drop('Unnamed: 0', axis =1 )
All_information.head()

,Unnamed: 0,date,sms_events,calls_events,data_events,mean_call_duration,mean_data_volume,mean_sms_cost,mean_call_cost,mean_data_cost,...,total_data_cost,total_cost,sms_ARPU,calls_ARPU,data_ARPU,total_ARPU,norm_sms_ARPU,norm_calls_ARPU,norm_data_ARPU,norm_total_ARPU
0,0,2020-01-01,93.40020,166.54317,819.98262,3.00548,73.89163,0.296020,0.23838,0.069640,...,57.103590,124.452478,0.485058,0.696501,1.001817,2.183377,0.638539,0.518889,0.756828,0.674542
1,1,2020-01-02,61.90280,128.52700,609.54177,2.95532,69.44602,0.279973,0.20090,0.066325,...,40.427858,83.580045,0.403049,0.600490,0.940183,1.943722,0.530580,0.447361,0.710265,0.600502
2,2,2020-01-03,26.63946,53.44308,253.16442,3.09473,72.13188,0.266676,0.24692,0.068270,...,17.283535,37.583805,0.394672,0.733120,0.960196,2.087989,0.519553,0.546170,0.725385,0.645072
3,3,2020-01-04,58.74116,117.83914,566.75936,3.02477,73.02448,0.295659,0.20518,0.068925,...,39.063889,80.609476,0.457036,0.636269,1.027997,2.121302,0.601649,0.474017,0.776605,0.655364
4,4,2020-01-05,13.51314,27.16119,128.09592,3.01652,73.46773,0.269902,0.21685,0.065050,...,8.332640,17.869767,0.405247,0.654434,0.925849,1.985530,0.533474,0.487549,0.699437,0.613418

In [30]:
All_information_main = All_information[:839]
All_information_main.to_csv('all_information.csv', index=False)
All_information_main

,Unnamed: 0,date,sms_events,calls_events,data_events,mean_call_duration,mean_data_volume,mean_sms_cost,mean_call_cost,mean_data_cost,...,total_data_cost,total_cost,sms_ARPU,calls_ARPU,data_ARPU,total_ARPU,norm_sms_ARPU,norm_calls_ARPU,norm_data_ARPU,norm_total_ARPU
0,0,2020-01-01,93.40020,166.54317,819.98262,3.00548,73.89163,0.296020,0.23838,0.069640,...,57.103590,124.452478,0.485058,0.696501,1.001817,2.183377,0.638539,0.518889,0.756828,0.674542
1,1,2020-01-02,61.90280,128.52700,609.54177,2.95532,69.44602,0.279973,0.20090,0.066325,...,40.427858,83.580045,0.403049,0.600490,0.940183,1.943722,0.530580,0.447361,0.710265,0.600502
2,2,2020-01-03,26.63946,53.44308,253.16442,3.09473,72.13188,0.266676,0.24692,0.068270,...,17.283535,37.583805,0.394672,0.733120,0.960196,2.087989,0.519553,0.546170,0.725385,0.645072
3,3,2020-01-04,58.74116,117.83914,566.75936,3.02477,73.02448,0.295659,0.20518,0.068925,...,39.063889,80.609476,0.457036,0.636269,1.027997,2.121302,0.601649,0.474017,0.776605,0.655364
4,4,2020-01-05,13.51314,27.16119,128.09592,3.01652,73.46773,0.269902,0.21685,0.065050,...,8.332640,17.869767,0.405247,0.654434,0.925849,1.985530,0.533474,0.487549,0.699437,0.613418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,834,2022-04-15,22489.66177,42260.56684,164017.54020,2.99101,80.95921,0.260532,0.30283,0.070430,...,11551.755356,30208.799373,0.595032,1.299662,1.173124,3.067818,0.783309,0.968240,0.886242,0.947785
835,835,2022-04-16,22100.19105,42032.00850,174462.14430,3.06963,78.81162,0.280855,0.28556,0.066215,...,11552.010885,29761.620389,0.627916,1.214230,1.168640,3.010786,0.826599,0.904593,0.882855,0.930165
836,836,2022-04-17,22869.09886,42800.43894,167690.88246,2.94031,79.34642,0.261898,0.26895,0.068260,...,11446.579637,28947.128943,0.602371,1.157717,1.151220,2.911307,0.792971,0.862492,0.869694,0.899432
837,837,2022-04-18,22741.87971,42291.12899,166043.14562,2.90155,73.42698,0.301781,0.30389,0.070295,...,11672.002921,31386.921311,0.692470,1.296726,1.177682,3.166877,0.911578,0.966053,0.889685,0.978389
838,838,2022-04-19,23248.42170,42833.08295,181387.29350,3.06639,76.99760,0.265234,0.27785,0.067040,...,12160.204156,30227.648135,0.622541,1.201532,1.227683,3.051757,0.819524,0.895133,0.927459,0.942823

In [31]:
All_information_last = All_information[839:]
All_information_last.to_csv('all_information_last.csv', index=False)
All_information_last

,Unnamed: 0,date,sms_events,calls_events,data_events,mean_call_duration,mean_data_volume,mean_sms_cost,mean_call_cost,mean_data_cost,...,total_data_cost,total_cost,sms_ARPU,calls_ARPU,data_ARPU,total_ARPU,norm_sms_ARPU,norm_calls_ARPU,norm_data_ARPU,norm_total_ARPU
839,839,2022-04-20,23519.12960,41768.35840,175209.91680,3.09580,81.77183,0.284617,0.28764,0.069515,...,12179.717366,30887.912086,0.674793,1.211114,1.227794,3.113701,0.888308,0.902272,0.927543,0.961960
840,840,2022-04-21,23809.74552,42991.28640,162329.40144,3.09578,81.43722,0.261850,0.28860,0.071190,...,11556.230089,30198.097208,0.625209,1.244212,1.158868,3.028289,0.823035,0.926930,0.875472,0.935573
841,841,2022-04-22,24085.27440,43171.87140,172710.93240,2.94730,78.45970,0.283533,0.26877,0.069685,...,12035.361324,30467.635307,0.681534,1.158014,1.201134,3.040682,0.897182,0.862713,0.907402,0.939401
842,842,2022-04-23,23180.51887,41962.89473,145123.17748,2.95527,74.42905,0.292336,0.26120,0.072430,...,10511.271745,28248.480013,0.675825,1.093119,1.048297,2.817241,0.889667,0.814367,0.791941,0.870371
843,843,2022-04-24,22830.94275,43244.37315,165893.64495,3.00389,83.12696,0.280809,0.29462,0.064505,...,10700.969567,29852.760988,0.636973,1.265838,1.063186,2.965997,0.838522,0.943041,0.803189,0.916328
844,844,2022-04-25,23194.70404,43512.20166,149311.01422,3.08319,79.16775,0.282022,0.30824,0.065470,...,9775.392101,29729.009963,0.651730,1.336276,0.973936,2.961942,0.857948,0.995517,0.735764,0.915075
845,845,2022-04-26,25375.90405,43485.16015,150110.19005,3.06124,81.07870,0.290785,0.29081,0.066055,...,9915.528604,29940.380286,0.733857,1.257675,0.986129,2.977661,0.966061,0.936960,0.744976,0.919931
846,846,2022-04-27,24778.83446,43851.06972,172360.92699,2.98676,74.77832,0.292698,0.30797,0.065990,...,11374.097572,32131.626803,0.720874,1.342293,1.130514,3.193681,0.948971,1.000000,0.854052,0.986670
847,847,2022-04-28,25595.79403,43731.82349,186081.65180,3.03331,74.07075,0.258271,0.28234,0.065525,...,12193.000234,31150.894598,0.654714,1.222863,1.207586,3.085163,0.861877,0.911025,0.912277,0.953144
848,848,2022-04-29,25144.51221,43387.87644,165643.50429,3.01726,76.40292,0.299744,0.29488,0.066990,...,11096.458352,31427.592025,0.741749,1.259149,1.092064,3.092963,0.976451,0.938058,0.825004,0.955553
849,849,2022-04-30,23498.15739,44110.84302,157103.34039,2.93226,73.51640,0.262277,0.29738,0.072395,...,11373.496328,30654.205051,0.603686,1.284914,1.114066,3.002665,0.794702,0.957252,0.841626,0.927656
850,850,2022-05-01,23626.72192,43232.62014,156906.57558,3.03469,79.45200,0.302200,0.30940,0.068060,...,10679.061534,31195.229570,0.698493,1.308567,1.044714,3.051774,0.919508,0.974874,0.789234,0.942828
851,851,2022-05-02,23631.27250,44781.12250,158539.10750,3.03444,80.11107,0.296533,0.30309,0.067895,...,10764.012704,31344.175250,0.683654,1.324167,1.050148,3.057968,0.899973,0.986496,0.793339,0.944742
852,852,2022-05-03,23660.24240,43646.72120,178735.79000,2.98896,73.98162,0.270006,0.29407,0.073190,...,13081.672470,32305.271183,0.621440,1.248559,1.272536,3.142536,0.818074,0.930169,0.961343,0.970869
853,853,2022-05-04,25901.57848,43487.86952,186546.55488,3.03718,77.04286,0.302429,0.28530,0.066455,...,12396.951305,32637.428957,0.759638,1.203170,1.202187,3.164995,1.000000,0.896354,0.908198,0.977807
854,854,2022-05-05,25378.26467,43483.30227,167310.69618,2.93568,80.32682,0.255422,0.30003,0.070550,...,11803.769615,31332.231914,0.629276,1.266508,1.145886,3.041669,0.828389,0.943540,0.865665,0.939706
855,855,2022-05-06,25409.19952,43822.86768,173859.48400,2.91038,78.62798,0.298095,0.26452,0.069115,...,12016.298237,31182.678526,0.736232,1.126752,1.167992,3.030976,0.969188,0.839423,0.882365,0.936403
856,856,2022-05-07,24649.91296,44655.13760,185787.94624,2.90841,80.12541,0.272958,0.27072,0.071130,...,13215.096616,32032.526409,0.650967,1.169605,1.278550,3.099122,0.856943,0.871348,0.965887,0.957456
857,857,2022-05-08,25003.18704,44065.23732,167237.97298,2.95569,81.46422,0.300261,0.29103,0.073505,...,12292.827204,32624.615165,0.727328,1.242425,1.190935,3.160687,0.957467,0.925598,0.899697,0.976476
858,858,2022-05-09,23338.55680,45063.73498,157441.27418,3.02942,80.06380,0.295374,0.28268,0.065660,...,10337.594063,29969.813543,0.669672,1.237480,1.004235,2.911387,0.881567,0.921915,0.758654,0.899456
859,859,2022-05-10,23422.97851,44022.96830,177213.79848,2.97753,81.97718,0.261737,0.30810,0.071735,...,12712.431834,32406.568493,0.593654,1.313399,1.230990,3.138043,0.781495,0.978474,0.929957,0.969480
860,860,2022-05-11,24848.55234,43359.49224,184547.61960,2.99126,79.91919,0.276880,0.29530,0.073800,...,13619.614326,33303.739557,0.668682,1.244441,1.323706,3.236830,0.880264,0.927101,1.000000,1.000000
861,861,2022-05-12,23451.90664,44569.58884,186501.48316,3.01646,79.00334,0.282913,0.29333,0.068455,...,12766.959030,32475.405787,0.646168,1.273237,1.243373,3.162778,0.850626,0.948553,0.939312,0.977122
862,862,2022-05-13,24987.05088,43223.34336,158373.38784,3.02210,82.24169,0.258096,0.27398,0.066340,...,10506.490549,28797.880047,0.627829,1.152875,1.022828,2.803532,0.826484,0.858884,0.772700,0.866135
863,863,2022-05-14,24079.89480,44123.98110,168614.07024,3.09376,75.52991,0.289169,0.27827,0.064845,...,10933.779385,30175.318705,0.675904,1.191844,1.061326,2.929074,0.889771,0.887916,0.801784,0.904921
864,864,2022-05-15,24084.10740,45021.68888,149483.80296,3.02981,77.29058,0.287712,0.28012,0.068080,...,10176.857306,29717.619503,0.674843,1.228231,0.991124,2.894197,0.888374,0.915024,0.748749,0.894146
865,865,2022-05-16,23893.06465,43614.21337,171706.56230,3.01109,80.60571,0.300125,0.29482,0.067845,...,11649.431719,31678.680133,0.697355,1.250447,1.132883,3.080685,0.918010,0.931575,0.855841,0.951760
866,866,2022-05-17,23704.10480,43747.37068,181935.86448,3.04066,78.98173,0.291508,0.27714,0.074000,...,13463.253972,32497.336464,0.669827,1.175276,1.305085,3.150188,0.881771,0.875573,0.985932,0.973232
867,867,2022-05-18,24319.84851,44845.34697,178556.10507,2.95731,78.73709,0.254181,0.26498,0.069375,...,12387.329789,30452.093243,0.595706,1.145140,1.193729,2.934576,0.784197,0.853122,0.901808,0.906620
868,868,2022-05-19,24688.44254,43978.85088,187217.05510,3.05488,73.86576,0.275304,0.29950,0.072560,...,13584.469518,33552.962342,0.651474,1.262500,1.302067,3.216042,0.857611,0.940555,0.983653,0.993578